### ISSUE TITLE
Is there some installation step missing that a newbie like me needs, in order to follow your installation & build instructions? 

### ISSUE THREAD

**Issue by darrenaddy** [4044ever/Hugo-Tailwind-4.x#1]
Thanks so much for providing this starter. I've been working with Hugo for about 4 months now and made a lot of Hugo sites to try out different themes, but I'm afraid I'm unclear on something with your README instructions. Am I supposed to create a `Hugo new site xxxxx` before doing this? If so, what directory should I be in when I run the:
`git clone https://github.com/4044ever/Hugo-Tailwind-3.0
npm install`
??

I thought it would create a Hugo Site for me, so I went into my HugoSites folder and issued the command.
This resulted in a:
HugoSites > Hugo-Tailwind-3.0 folder 
and a 
HugoSites > package.json

Doing your next step:
`npm run start`
(from where I was - without moving into the Hugo-Tailwind-3.0 folder)
resulted in this:

```
D:\Hugo\HugoSites>npm install
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path D:\Hugo\HugoSites/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'D:\Hugo\HugoSites\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent
```
However, this file DOES exist: 
 'D:\Hugo\HugoSites\package.json'

Is there some step missing that a newbie like me needs, in order to follow your installation & build instructions? Thanks in advance for any reply you may have time to provide!

**Comment by darrenaddy** [comment]
OK, I figured it out.
Basically you have to open the Hugo-Tailwind-3.0 folder in VScode. Then open the terminal in VScode and issue the commands.

I created an empty style.css file in assets/css
Still, the first time I entered `npm run start`
I got an error building the site: 
Error: Error building site: POSTCSS: failed to transform "css/style.css" (text/css): Input Error: Did not receive any STDIN
It finished with `Built in 3420 ms` but seemed stuck there (no joy at localhost:1313)
So I did a Cntl-C to terminate the batch process and tried `npm run start` again.
This time it built fine in 3701 ms and gave me the localhost:1313 message.

So Hugo-Tailwind-3.0 **is** the HugoSite but contains no theme.
So I would next do a `hugo new theme themename` that will use the partial head.html file in the parent folder to call Tailwind.
Do I have that straight? TIA!

**Comment by 4044ever** [comment]
So sorry, did see your message late. 

You need to have the Hugo environment in the `/bin/` but no need to create a Hugo site. Do simply:

`git clone https://github.com/4044ever/Hugo-Tailwind-3.0 npm install hugofolder`
`cd hugofolder`
`npm install`
`npm run start`

I prefer to do my own layout, I don't use off the shelf themes. I find it hard to adjust other peoples themes.

Yeah, sometimes things work the 2nd way round. Not sure why. 

I do not use a theme, I write my own layout because I find it difficult to adjust other peoples themes. 

Here an examples site sort of based on my repo: https://scale-pizza.netlify.app/

**Comment by anujb** [comment]
@4044ever do you turn your own layouts into themes and then use them in your hugo sites? I want to combine this Tailwind repo with another minimalist theme. How would you recommend I go about doing this?

I just tried using a theme, and it looks like this didn't quite work out well because I had to run the `npm` command inside the theme directly. When I really just want a one-command build pipeline. 

...so I guess I answered my own question and need to use the theme as the main hugo site and adapt it.
